### PR TITLE
v0.12.0 support

### PR DESCRIPTION
**Pull request by adkelley**

### CODE REVIEW

**Comment by kritzcreek** [comment]
Thanks, the reason this fails is because the newest purescript-node-bin requires at least node-8. The way we fixed this in the other repos is by changing the .travis.yml to point at nodejs: stable.

Fwiw this library already works fine on 0.12, it's just not tested on CI against that compiler version.

**Comment by adkelley** [comment]
Got it.  If I understand you correctly, is this just a matter of changing .travis.yml to point to nodejs: stable?  I'd like to get this into psc-package-sets because it's a dependency for purescript-webaudio

**Comment by garyb** [comment]
I don't think you need to do anything to update it for a package set - it needed no code changes for 0.12 and has no dependencies, so it should be possible to just add it straight in.

**Comment by thomashoneyman** [comment]
Hey folks! This is a transitive dependency for a library of ours at CitizenNet. I looked at the Travis failure and it does look like switching o node "stable" will let that run (I've seen a similar problem in other repositories). 

@adkelley any chance you could update the PR with that change and then if CI passes we can get this merged?

Thanks!

**Comment by kritzcreek** [comment]
@thomashoneyman This library works fine as is on 0.12, so don't worry about this PR, just use the latest version.

**Comment by thomashoneyman** [comment]
Sheesh, I was just reading the source and Bower file and noticed that there's nothing to do. Thanks!

**Comment by thomashoneyman** [comment]
Merging this to tie up loose ends and will fix the Travis build as well.

**Pull request merged**
